# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LogGraphDemo' do
	pod 'OCUtilCollection', :git => "https://github.com/EdgarHz/OCUTLCollection.git"
	pod 'JSONModel', '~> 1.2.0'
end

target 'LogGraphDemoTests' do

end

target 'LogGraphDemoUITests' do

end

